[default.extend-words]
# abbreviations
FRE = "FRE"
wrk = "wrk"
fo = "fo"
odf = "odf"
ODF = "ODF"
pn = "pn"
PN = "PN"
Ond = "Ond"
ths = "ths"
gti = "gti"
Ded = "Ded"
ue = "ue"
# tags
curren = "curren"
Thi = "Thi"
pard = "pard"
BA = "BA"
PARD = "PARD"
Evn = "Evn"
ment = "ment"
FO = "FO"
FOF = "FOF"
ture = "ture"
headerr = "headerr"
# non-English words or odd spellings
recommande = "recommande"
Persan = "Persan"
ist = "ist"
oder = "oder"
BERKLEY = "BERKLEY"
Programa = "Programa"
objets = "objets"
sur = "sur"
Hel = "Hel"
caf = "caf"
som = "som"
Som = "Som"
mor = "mor"
WORL = "WORL"

[type.svg]
extend-glob = ["*.svg"]
check-file = false
